name: Revert Last Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  revert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Revert Last Commit
        run: |
          LAST_COMMIT=$(git rev-parse HEAD)

          git revert --no-edit $LAST_COMMIT

      - name: Push Changes
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          git push origin "$BRANCH"